name: Laravel Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  laravel-deploy:

    runs-on: ubuntu-24.04

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring, pdo, mysql

    - uses: actions/checkout@v4

    - name: Copy .env file
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --prefer-dist

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Set Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Set up SSH for deployment
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}  # Your EC2 IP address as a secret
        username: ubuntu  # or ec2-user, depending on your EC2 AMI
        key: ${{ secrets.SSH_PRIVATE_KEY }}  # Your private key
        port: 22
        script: |
          cd /var/www/html/blog &&
          git pull origin main &&
          composer install --no-dev &&
          php artisan migrate --force &&
          php artisan cache:clear &&
          php artisan config:cache &&
          php artisan route:cache &&
          sudo service apache2 restart
    
