name: Laravel Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  laravel-deploy:

    runs-on: ubuntu-24.04

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring, pdo, mysql

    - uses: actions/checkout@v4

    - name: Copy .env file
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --prefer-dist

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Set Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Set up SSH for deployment
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@65.0.177.219 "
          cd /var/www/html/your-laravel-project &&
          git pull origin main &&
          composer install --no-dev &&
          php artisan cache:clear &&
          php artisan config:cache &&
          php artisan route:cache &&
          sudo service apache2 restart
        "

